name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: ./.github/workflows/release-please.yaml
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit
